sudo: required
services:
  - docker

before_install:
  - docker build -t yogasab/docker-react-playground -f Dockerfile.dev .

script:
  - docker run yogasab/docker-react-playground npm run test -- --coverage
